- name: Create Kubernetes cluster components
  hosts: localhost
  gather_facts: false
  vars:
    count: "{{ controllers if role == 'controller' else workers }}"
    state: present
    build_infra: true

  tasks:
  - name: Load local variables
    include_vars:
      dir: host_vars
      ignore_unknown_extensions: True
      extensions: ['yaml']

  - import_tasks: network.yaml
    when: build_infra == true
  - import_tasks: subnetwork.yaml
    when: build_infra == true
  - import_tasks: firewall.yaml
    when: build_infra == true
  - import_tasks: balancer.yaml
    when: build_infra == true
  - import_tasks: disks.yaml
    when: build_infra == true
  - import_tasks: ip-address.yaml
    when: build_infra == true
  - import_tasks: compute-instances.yaml
    when: build_infra == true

  - meta: refresh_inventory
  - pause:
      minutes: 1

- name: Run basic provision
  hosts: all
  become: true
  gather_facts: false

  tasks:
  - import_tasks: basic_provision.yaml

  handlers:
    - name: reload_systemd
      systemd:
        daemon_reload: yes

    - name: restart_containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes

    - name: kernel_mods_reload
      shell: |
        modprobe "{{ item }}"
      loop:
        - overlay
        - br_netfilter

    - name: reload_sysctl
      shell: |
        sysctl --system

- name: Installing client Tools
  hosts: all
  become: true
  gather_facts: false

  tasks:
  - import_tasks: tools.yaml
