- name: Create Kubernetes cluster components
  hosts: localhost
  gather_facts: false
  vars:
    count: "{{ controllers if role == 'controller' else workers }}"
    state: present

  tasks:
  - name: Load local variables
    include_vars:
      dir: host_vars
      ignore_unknown_extensions: True
      extensions: ['yaml']

  - import_tasks: network.yaml
    when: build_infra == true
  - import_tasks: subnetwork.yaml
    when: build_infra == true
  - import_tasks: firewall.yaml
    when: build_infra == true
  - import_tasks: balancer.yaml
    when: build_infra == true
  - import_tasks: disks.yaml
    when: build_infra == true
  - import_tasks: ip-address.yaml
    when: build_infra == true
  - import_tasks: compute-instances.yaml
    when: build_infra == true

- name: Run basic provision
  hosts: "{{ role }}"
  become: true
  gather_facts: false

  tasks:
  - import_tasks: basic_provision.yaml

- name: Installing client Tools
  hosts: controller
  become: true
  gather_facts: false

  tasks:
  - import_tasks: client_tools.yaml
