- name: Create Kubernetes cluster components
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Load local variables
    include_vars:
      dir: host_vars
      ignore_unknown_extensions: True
      extensions: ['yaml']

  - import_tasks: network.yaml
  - import_tasks: subnetwork.yaml
  - import_tasks: firewall.yaml
  - import_tasks: balancer.yaml
  - import_tasks: disks.yaml
  - import_tasks: ip-address.yaml
  - import_tasks: compute-instances.yaml
